### ISSUE TITLE
winter17 - talk4 - how to make a kickass data science project from start to finish

### ISSUE THREAD

**Issue by friedeggs** [uwaterloo-datascience/talks#5]
Somewhat similar to the talk1 reproducibility idea (maybe merge with talk1?), but a more holistic look geared for people who are interested in working on a project and aren't sure how to get going.

Discussion ideas:
- as an example, one or two great data science projects by people in the community (eg [Machine Learning meets Ketosis](https://github.com/arielf/weight-loss)) (know any other good data science project examples?)
- choosing an idea
- choosing the tools & methods for executing the idea
- doing background research
- data collection 
- software engineering tips
  - best coding practices and code style
- statistics tips 
  - tips for conducting analyses
- making your work presentable (code, writeup) and telling people about it
- pitfalls to avoid
- why work on a data science project in the first place?

**Comment by jxnl** [comment]
1) so how long do you think this will take to actually present? 

2) what does code style mean in the context of data science. analysis style? mark up?

3) statistics tips can get really detailed and specific 

--- 

I feel like this is huge in scope. Is this a one hour panel where some experienced data scientists sit at the front and discuss? are you presenting this?
